/* autogenerated by Processing revision 1292 on 2023-07-25 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Spectrum extends PApplet {

PImage mazeMap, cake;
PImage map;
public void setup(){
  /* size commented out by preprocessor */;
  background(0);
  frameRate(60);
  cake = loadImage("data/images/cake.jpeg");
  mazeMap = loadImage("data/images/200by200orthogonalmaze.png");
  mazeMap.resize(height*20,0);
  mazeMap.filter(INVERT);
  //mazeMap.filter(BLUR,4);
  mazeMap.filter(THRESHOLD);
  map = mazeMap;
  p = new Player(map.width/2-width/2-50, -height/2+80);
}
float angle;
int xPos = 0;
int yPos = 0;
float lightDensity = 150;
float pulseFrequency = 20;
int wl = 380;
public void draw(){
  p.playerMove();
  p.updateMovement();
  p.updateRealPosition();
  spawnLight();
  for(Light a: L){
    a.updateMovement();
  }
  for(int i = L.size()-1; i > 0; i--){
    Light a = L.get(i);
    if(a.delete()){
      L.remove(i);
    }
  }
  
  background(0);
  pushMatrix();
  p.translateMove();
  //drawMap();
  drawText();
  for(Light a: L){
    a.show();
    a.showReflected();
  }
  //fill(255);
  //llipse(p.xRPos, p.yRPos, 10, 10);
  popMatrix();
  showText();
}
public void mouseWheel(MouseEvent event){
  //if(wl >= 380 && wl <= 750){
    wl += 5*event.getCount();
  //} else {
  //  wl += 25*event.getCount();
  //}
  if(wl < -3000)
    wl = -3000;
  if(wl > 4999)
    wl = 4999;
}
public void keyPressed(){
  p.setMove(keyCode, true);
}
public void keyReleased(){
  p.setMove(keyCode, false);
}
public int wavelenghtToRGB(int wavelength) {
  float r, g, b;
  if (wavelength >= 380 && wavelength < 440) {
    // Violet
    r = (-(wavelength - 440.0f) / (440.0f - 380.0f))*255.0f;
    g = 0.0f;
    b = 255.0f;
  } else if (wavelength >= 440 && wavelength < 490) {
    // Blue
    r = 0.0f;
    g = ((wavelength - 440.0f) / (490.0f - 440.0f))*255.0f;
    b = 255.0f;
  } else if (wavelength >= 490 && wavelength < 510) {
    // Cyan
    r = 0.0f;
    g = 255.0f;
    b = (-(wavelength - 510.0f) / (510.0f - 490.0f))*255.0f;
  } else if (wavelength >= 510 && wavelength < 580) {
    // Green
    r = ((wavelength - 510.0f) / (580.0f - 510.0f))*255.0f;
    g = 255.0f;
    b = 0.0f;
  } else if (wavelength >= 580 && wavelength < 645) {
    // Yellow
    r = 255.0f;
    g = (-(wavelength - 645.0f) / (645.0f - 580.0f))*255.0f;
    b = 0.0f;
  } else if (wavelength >= 645 && wavelength <= 750) {
    // Red
    r = 255.0f;
    g = 0.0f;
    b = 0.0f;
  } else {
    r = 0.0f;
    g = 0.0f;
    b = 0.0f;
  }
  return color(r, g, b);
}
public int roundWavelength(int wavelength) {
  if (wavelength >= 380 && wavelength < 440) {
    // Violet
    return 400;
  } else if (wavelength >= 440 && wavelength < 490) {
    // Blue
    return 450;
  } else if (wavelength >= 490 && wavelength < 510) {
    // Cyan
    return 500;
  } else if (wavelength >= 510 && wavelength < 580) {
    // Green
    return 550;
  } else if (wavelength >= 580 && wavelength < 645) {
    // Yellow
    return 600;
  } else if (wavelength >= 645 && wavelength <= 750) {
    // Red
    return 700;
  } else {
    // Black
    return 0;
  }
}
public int RGBToRoundWavelength(float r, float g, float b) {
  if(r > 230 && g > 230 && b > 230){
    // White
    return 0;
  }
  if(g == 0 && b == 255){
    // Violet
    return 400;
  } else if (r == 0 && b == 255) {
    // Blue
    return 450;
  } else if (r == 0 && g == 255) {
    // Cyan
    return 500;
  } else if (g == 255 && b == 0) {
    // Green
    return 550;
  } else if (r == 255 && g != 0 && b == 0) {
    // Yellow
    return 600;
  } else if (r == 255 && g == 0 && b == 0) {
    // Red
    return 700;
  } else {
    // Black
    return -1;
  }
}
ArrayList<Light> L = new ArrayList<Light>();
public void spawnLight(){
  if(frameCount % pulseFrequency==0){
    for(int i = 0; i<lightDensity; i++){
      L.add(new Light(p.xRPos, p.yRPos, angle, wl));
      angle += 2*PI/lightDensity;
    }
  }
}
class Light{
  int fluorescence = 50;
  boolean reflected = false;
  int alpha = 50;
  int speed = 10;
  int timeSpan = 100;
  int timePassed = 0;
  //xpos, ypos, wavelength, roundWavelength
  int wl, rwl;
  float angle, vx, vy, x, y;
  int c;
  Light(float x, float y, float a ,int wl){
    this.x = x;
    this.y = y;
    this.wl = wl;
    rwl = roundWavelength(wl);
    this.angle = a;
    c = wavelenghtToRGB(wl);
    vx = cos(a)*speed;
    vy = sin(a)*speed;
  }
  public void updateMovement(){
    if(!reflected){
      x += vx+random(-5,5);
      y += vy+random(-5,5);
      reflection();
    } else {
      x += vx;
      y += vy;
    }
    timePassed++;
  }
  public void showReflected(){
    if(reflected){
      fill(c,(PApplet.parseInt((timeSpan-timePassed)*255/fluorescence)));
      noStroke();
      ellipse(x, y, 10, 10);
    }
  }
  public void show(){
    fill(c,alpha);
    noStroke();
    ellipse(x, y, 10, 10); 
  }
  public void reflection(){
    if(x>0 && x<map.width && y>0 && y<map.height){
      int pixel = map.pixels[PApplet.parseInt(y)*map.width+PApplet.parseInt(x)];
      if(red(pixel) != 0 || green(pixel) != 0 || blue(pixel) != 0){
        int objectWl = RGBToRoundWavelength(red(pixel),green(pixel),blue(pixel));
        if(objectWl == rwl ||(objectWl == 0)){
          vx *= 0.005f;
          vy *= 0.005f;
          timeSpan = timePassed+fluorescence;
          //vx *= -1;
          //vy *= -1;
          //timeSpan = timePassed*2;
          reflected = true;
          //c = color(255);
          alpha = 200;
        }
      }
    }
  }
  public boolean delete(){
    if(timePassed > timeSpan)
      return true;
    else
      return false;
  }
}
int red = wavelenghtToRGB(700);
int green = wavelenghtToRGB(550);
int white = color(255,255,255);
public void drawMap(){
  image(map,0,0);
  /*fill(red);
  rect(600,400,100,100);
  fill(green);
  ellipse(1000,600,40,40);
  fill(white);
  rect(400,600,50,50);
  rect(42.0, 29.0, 118.0, 118.0);
  rect(40.0, 121.0, 104.0, 104.0);
  rect(70.0, 197.0, 125.0, 125.0);
  rect(74.0, 275.0, 130.0, 130.0);
  rect(46.0, 318.0, 162.0, 162.0);
  rect(72.0, 398.0, 101.0, 101.0);
  line(96.0, 85.0, 95.0, 129.0);
  line(93.0, 130.0, 93.0, 132.0);
  line(100.0, 87.0, 184.0, 165.0);
  line(131.0, 133.0, 255.0, 264.0);
  line(145.0, 157.0, 188.0, 257.0);
  line(121.0, 74.0, 89.0, 214.0);*/
}
Player p;

class Player{
  boolean isUp, isDown, isLeft, isRight;
  float speed = 5;
  float xVel, yVel, xRPos, yRPos;
  int pxPos, pyPos, xPos, yPos;
  Player(float xPos, float yPos){
    this.xPos = PApplet.parseInt(xPos);
    this.yPos = PApplet.parseInt(yPos);
  } 
  public void display(){
  }
  public void setMove(int k, boolean isPressed){
    switch(k){
      case 'A':
        isLeft = isPressed;
        break;
      case 'S':
        isDown = isPressed;
        break;
      case 'D':
        isRight = isPressed;
        break;
      case 'W':
        isUp = isPressed;
        break;
    }
  }
  public void playerMove(){
    if(isRight){
      xVel = speed;
    }
    if(isLeft){
      xVel = -speed;
    }
    if(isUp){
      yVel = -speed;
    }
    if(isDown){
      yVel = speed;
    }
  }
  public boolean checkCollision(){
    if(xRPos > speed && xRPos < map.width-speed && /*yRPos > speed &&*/ yRPos < map.height-speed){
      if(brightness(map.pixels[PApplet.parseInt(yPos + height/2)*map.width+PApplet.parseInt(xPos + width/2)]) > 210){
        if(xPos > pxPos) xPos--;
        if(xPos < pxPos) xPos++;
        if(yPos > pyPos) yPos--;
        if(yPos < pyPos) yPos++;
        return true;
      }else{
        pxPos = xPos;
        pyPos = yPos;
        return false;
      }
    }else{
      return false;
    }
  }
  public void updateMovement(){
    for(int i = 0; i < xVel; i++){
      xPos++;
      if(checkCollision()) break;
    }
    for(int i = 0; i > xVel; i--){
      xPos--;
      if(checkCollision()) break;
    }
    for(int i = 0; i < yVel; i++){
      yPos++;
      if(checkCollision()) break;
    }
    for(int i = 0; i > yVel; i--){
      yPos--;
      if(checkCollision()) break;
    }
    xVel = 0;
    yVel = 0;
  }
  public void translateMove(){
    translate(-xPos, -yPos);
  }
  public void playerEffects(){
    
  }
  public void updateRealPosition(){
    xRPos = xPos + width/2;
    yRPos = yPos + height/2;
  }
}
float pp, xoff;
public void prect(float x, float y, float w, float h){
  rect(x*pp+xoff, y*pp, w*pp, h*pp);
}
public void pline(float x, float y, float x2, float y2){
  line(x*pp+xoff, y*pp, x2*pp+xoff, y2*pp);
}
public void pellipse(float x, float y, float w, float h){
  ellipse(x*pp+xoff, y*pp, w*pp, h*pp);
}
public void showText(){
  textSize(25);
  textAlign(CENTER, CENTER);
  fill(200);
  if(wl>=0 && wl<1000){
    text(wl+1 + "nm",height/2,100);
  }else if(wl>=1000 && wl<2000){
    text(wl-999 + "µm",height/2,100);
  }else if(wl>=2000 && wl<3000){
    text(wl-1999 + "mm",height/2,100);
  }else if(wl>=3000 && wl<4000){
    text(wl-2999 + "m",height/2,100);
  }else if(wl>=4000){
    text(wl-3999 + "km",height/2,100);
  }else if(wl>=-1000 && wl<0){
    text(wl+1001 + "pm",height/2,100);
  }else if(wl>=-2000 && wl<-1000){
    text(wl+2001 + "fm",height/2,100);
  }else if(wl<-2000){
    text(wl+3001 + "am",height/2,100);
  }
  if(wl >= 380 && wl <= 750){
    text("<Visible Light>",height/2,50);
  }else if(wl > 750 && wl <= 1100){
    text("<Infrated>",height/2,50);
  }else if(wl > 1000 && wl <= 2010){
    text("<Radar>",height/2,50);
  }else if(wl > 2010 && wl <= 3100){
    text("<FM/TV>",height/2,50);
  }else if(wl > 3100 && wl <= 4010){
    text("<ShortWave>",height/2,50);
  }else if(wl > 4010){
    text("<AM>",height/2,50);
  }else if(wl < 380 && wl >= -900){
    text("<UltraViolet>",height/2,50);
  }else if(wl < -900 && wl >= -2009){
    text("<X-Ray>",height/2,50);
  }else if(wl < -2009){
    text("<GammaRay>",height/2,50);
  }
  
  fill(255);
  //text(p.xPos, 100, 10);
  //text(p.yPos, 100, 50);
  text("use wasd para mover",width/2,height-100);
  
}
public void drawText(){
  fill(255);
  textSize(50);
  textAlign(CENTER, CENTER);
  text("Não vá por cima",map.width/2-width/2+500,-height/2+200);
  text("Você passou! 6969",map.width/2-width/2+400,map.height+height/2+200);
  image(cake,map.width/2-width/2+200,map.height+height/2+300);
}


  public void settings() { size(900, 900, P2D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Spectrum" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
